# dindPodTemplate.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    agent: dind
spec:
  securityContext:
    runAsUser: 0
  containers:
    - name: "{{CONTAINER_NAME}}"  # Placeholder for main container
      image: "" # Image will be set by the script
      imagePullPolicy: Always
      command: ["cat"] # Keep the container running. Use a minimal command.
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
    - name: dind
      image: "docker:dind"
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-socket
      emptyDir: {}