apiVersion: v1
kind: Pod
metadata:
  labels:
    agent: dind
spec:
  securityContext:
    runAsUser: 0
  containers:
    - name: "{{CONTAINER_NAME}}" # Use placeholder for main container name
      image: "" # Image will be set by the script
      imagePullPolicy: Always
      args: ["jenkins-agent"]
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
    - name: dind
      image: "docker:dind"
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-socket
      emptyDir: {}