apiVersion: v1
kind: Pod
metadata:
  labels:
    agent: "{{CONTAINER_NAME}}"
spec:
  containers:
    - name: "{{CONTAINER_NAME}}"
      image: "{{POD_IMAGE}}:{{POD_IMAGE_VERSION}}"
      imagePullPolicy: Always
      args: ["jenkins-agent"]
      tty: true